__description__ =\
"""
Purpose: Module for creating a streamlined restriction enzyme.
"""
__author__ = "Erick Samera"
__version__ = "1.0.0"
__comments__ = "fast enough"
# --------------------------------------------------
import re
# --------------------------------------------------
class RestrictionEnzyme:
    def __init__(self, name: str, cut_sequence: str, overhang: str, incubation_temp: int, buffer: str, time_saver: bool, heat_inactivated: bool) -> None:
        """Create a restriction enzyme"""
        _degenerate_nucleotides = {
            'W': '[A|T]',
            'S': '[C|G]',
            'M': '[A|C]',
            'K': '[G|T]',
            'R': '[A|G]',
            'Y': '[C|T]',
            'B': '[C|G|T]',
            'D': '[A|G|T]',
            'H': '[A|C|T]',
            'V': '[A|C|G]',
            'N': '[A|C|T|G]'
        }

        self.name: str = str(name)
        self.overhang: str = str(overhang)
        self.incubation_temp: int = int(incubation_temp)
        self.buffer: str = str(buffer)
        self.time_saver: bool = True if time_saver == 'True' else False
        self.heat_inactivated: bool = True if heat_inactivated == 'True' else False

        self.regex_restriction_site = cut_sequence
        for degenenerate_nucleotide, regex_equiv in _degenerate_nucleotides.items():
            self.regex_restriction_site = self.regex_restriction_site.replace(degenenerate_nucleotide, regex_equiv)
        self.regex_restriction_site = self.regex_restriction_site.replace('^', '').replace('_', '')

        self.cut_sequence_str: str = cut_sequence
        self.recognition_site: str = cut_sequence.replace('^', '').replace('_', '')
        self.cut_site: int = cut_sequence.index('^')
        return None
    def __repr__(self):
        return f"<{self.name}: {self.cut_sequence_str}, {self.regex_restriction_site}>"
    def catalyze(self, target_sequence: str):
        """Perform catalysis on a sequence and return the fragments"""
        re_pattern = re.compile(self.regex_restriction_site, flags=re.IGNORECASE)
        re_matches = re.finditer(re_pattern, str(target_sequence))
        match_positions: list = [0] + [m.start()+self.cut_site for m in re_matches] + [len(str(target_sequence))]
        fragments: list = [(target_sequence[match_positions[i]:match_positions[i+1]]) for i, _ in enumerate(match_positions) if i < len(match_positions)-1]
        return fragments
    def fast_catalyze(self, target_sequence: str):
        """Perform catalysis on a sequence and return the fragments"""
        re_pattern = re.compile(self.regex_restriction_site, flags=re.IGNORECASE)
        re_matches = re.finditer(re_pattern, str(target_sequence))
        match_positions: list = [0] + [m.start()+self.cut_site for m in re_matches] + [len(str(target_sequence))]
        fragments: list = [(match_positions[i], match_positions[i+1]) for i, _ in enumerate(match_positions) if i < len(match_positions)-1]
        return fragments

AatII=RestrictionEnzyme('AatII', 'G_ACGT^C', '3′', 37, 'rCutSmart', True, True)
AbaSI=RestrictionEnzyme('AbaSI', 'hCNNNNNNNNNN_NN^', '3′', 25, 'rCutSmart', False, True)
Acc65I=RestrictionEnzyme('Acc65I', 'G^GTAC_C', '5′', 37, 'NEB r3.1', True, True)
AccI=RestrictionEnzyme('AccI', 'GT^MK_AC', '5′', 37, 'rCutSmart', True, True)
AciI=RestrictionEnzyme('AciI', 'C^CG_C', '5′', 37, 'rCutSmart', True, True)
AclI=RestrictionEnzyme('AclI', 'AA^CG_TT', '5′', 37, 'rCutSmart', True, False)
AcuI=RestrictionEnzyme('AcuI', 'CTGAAGNNNNNNNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
AfeI=RestrictionEnzyme('AfeI', 'AGC_^GCT', 'Blunt', 37, 'rCutSmart', False, True)
AflII=RestrictionEnzyme('AflII', 'C^TTAA_G', '5′', 37, 'rCutSmart', True, True)
AflIII=RestrictionEnzyme('AflIII', 'A^CRYG_T', '5′', 37, 'NEB r3.1', False, True)
AgeI=RestrictionEnzyme('AgeI', 'A^CCGG_T', '5′', 37, 'NEB r1.1', False, True)
AgeI_HF=RestrictionEnzyme('AgeI-HF', 'A^CCGG_T', '5′', 37, 'rCutSmart', True, True)
AhdI=RestrictionEnzyme('AhdI', 'GACNN_N^NNGTC', '3′', 37, 'rCutSmart', True, True)
AleI_v2=RestrictionEnzyme('AleI-v2', 'CACNN_^NNGTG', 'Blunt', 37, 'rCutSmart', False, True)
AluI=RestrictionEnzyme('AluI', 'AG_^CT', 'Blunt', 37, 'rCutSmart', True, True)
AlwI=RestrictionEnzyme('AlwI', 'GGATCNNNN^N_', '5′', 37, 'rCutSmart', False, False)
AlwNI=RestrictionEnzyme('AlwNI', 'CAG_NNN^CTG', '3′', 37, 'rCutSmart', True, True)
ApaI=RestrictionEnzyme('ApaI', 'G_GGCC^C', '3′', 37, 'rCutSmart', True, True)
ApaLI=RestrictionEnzyme('ApaLI', 'G^TGCA_C', '5′', 37, 'rCutSmart', True, False)
ApeKI=RestrictionEnzyme('ApeKI', 'G^CWG_C', '5′', 75, 'NEB r3.1', True, False)
ApoI=RestrictionEnzyme('ApoI', 'R^AATT_Y', '5′', 50, 'NEB r3.1', True, True)
ApoI_HF=RestrictionEnzyme('ApoI-HF', 'R^AATT_Y', '5′', 37, 'rCutSmart', True, True)
AscI=RestrictionEnzyme('AscI', 'GG^CGCG_CC', '5′', 37, 'rCutSmart', True, True)
AseI=RestrictionEnzyme('AseI', 'AT^TA_AT', '5′', 37, 'NEB r3.1', True, True)
AsiSI=RestrictionEnzyme('AsiSI', 'GCG_AT^CGC', '3′', 37, 'rCutSmart', False, True)
AvaI=RestrictionEnzyme('AvaI', 'C^YCGR_G', '5′', 37, 'rCutSmart', True, True)
AvaII=RestrictionEnzyme('AvaII', 'G^GWC_C', '5′', 37, 'rCutSmart', True, True)
AvrII=RestrictionEnzyme('AvrII', 'C^CTAG_G', '5′', 37, 'rCutSmart', True, False)
BaeGI=RestrictionEnzyme('BaeGI', 'G_KGCM^C', '3′', 37, 'NEB r3.1', True, True)
BaeI=RestrictionEnzyme('BaeI', '_NNNNN^NNNNNNNNNNNACNNNNGTAYCNNNNNNNN_NNNNN^', '3′', 37, 'rCutSmart', True, True)
BamHI=RestrictionEnzyme('BamHI', 'G^GATC_C', '5′', 37, 'NEB r3.1', True, False)
BamHI_HF=RestrictionEnzyme('BamHI-HF', 'G^GATC_C', '5′', 37, 'rCutSmart', True, False)
BanI=RestrictionEnzyme('BanI', 'G^GYRC_C', '5′', 37, 'rCutSmart', False, True)
BanII=RestrictionEnzyme('BanII', 'G_RGCY^C', '3′', 37, 'rCutSmart', False, True)
BbsI=RestrictionEnzyme('BbsI', 'GAAGACNN^NNNN_', '5′', 37, 'NEB r2.1', True, True)
BbsI_HF=RestrictionEnzyme('BbsI-HF', 'GAAGACNN^NNNN_', '5′', 37, 'rCutSmart', True, True)
BbvCI=RestrictionEnzyme('BbvCI', 'CC^TCA_GC', '5′', 37, 'rCutSmart', False, False)
BbvI=RestrictionEnzyme('BbvI', 'GCAGCNNNNNNNNN^NNNN_', '5′', 37, 'rCutSmart', True, True)
BccI=RestrictionEnzyme('BccI', 'CCATCNNNN^N_', '5′', 37, 'rCutSmart', False, True)
BceAI=RestrictionEnzyme('BceAI', 'ACGGCNNNNNNNNNNNNN^NN_', '5′', 37, 'NEB r3.1', False, True)
BcgI=RestrictionEnzyme('BcgI', '_NN^NNNNNNNNNNNCGANNNNNNTGCN_NN^', '3′', 37, 'NEB r3.1', False, True)
BciVI=RestrictionEnzyme('BciVI', 'GTATCCNNNNNN_N^', '3′', 37, 'rCutSmart', True, True)
BclI=RestrictionEnzyme('BclI', 'T^GATC_A', '5′', 50, 'NEB r3.1', True, False)
BclI_HF=RestrictionEnzyme('BclI-HF', 'T^GATC_A', '5′', 37, 'rCutSmart', True, True)
BcoDI=RestrictionEnzyme('BcoDI', 'GTCTCN^NNNN_', '5′', 37, 'rCutSmart', True, False)
BfaI=RestrictionEnzyme('BfaI', 'C^TA_G', '5′', 37, 'rCutSmart', False, True)
BfuAI=RestrictionEnzyme('BfuAI', 'ACCTGCNNNN^NNNN_', '5′', 50, 'NEB r3.1', True, True)
BglI=RestrictionEnzyme('BglI', 'GCCN_NNN^NGGC', '3′', 37, 'NEB r3.1', True, True)
BglII=RestrictionEnzyme('BglII', 'A^GATC_T', '5′', 37, 'NEB r3.1', True, False)
BlpI=RestrictionEnzyme('BlpI', 'GC^TNA_GC', '5′', 37, 'rCutSmart', True, False)
BmgBI=RestrictionEnzyme('BmgBI', 'CAC_^GTC', 'Blunt', 37, 'NEB r3.1', True, True)
BmrI=RestrictionEnzyme('BmrI', 'ACTGGGNNNN_N^', '3′', 37, 'NEB r2.1', False, True)
BmtI=RestrictionEnzyme('BmtI', 'G_CTAG^C', '3′', 37, 'NEB r3.1', False, True)
BmtI_HF=RestrictionEnzyme('BmtI-HF', 'G_CTAG^C', '3′', 37, 'rCutSmart', True, True)
BpmI=RestrictionEnzyme('BpmI', 'CTGGAGNNNNNNNNNNNNNNN_NN^', '3′', 37, 'NEB r3.1', False, True)
Bpu10I=RestrictionEnzyme('Bpu10I', 'CC^TNA_GC', '5′', 37, 'NEB r3.1', False, True)
BpuEI=RestrictionEnzyme('BpuEI', 'CTTGAGNNNNNNNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
BsaAI=RestrictionEnzyme('BsaAI', 'YAC_^GTR', 'Blunt', 37, 'rCutSmart', True, False)
BsaBI=RestrictionEnzyme('BsaBI', 'GATNN_^NNATC', 'Blunt', 60, 'rCutSmart', False, True)
BsaHI=RestrictionEnzyme('BsaHI', 'GR^CG_YC', '5′', 37, 'rCutSmart', True, True)
BsaI_HFv2=RestrictionEnzyme('BsaI-HFv2', 'GGTCTCN^NNNN_', '5′', 37, 'rCutSmart', True, True)
BsaJI=RestrictionEnzyme('BsaJI', 'C^CNNG_G', '5′', 60, 'rCutSmart', False, True)
BsaWI=RestrictionEnzyme('BsaWI', 'W^CCGG_W', '5′', 60, 'rCutSmart', True, True)
BsaXI=RestrictionEnzyme('BsaXI', '_NNN^NNNNNNNNNNACNNNNNCTCCNNNNNNNN_NNN^', '3′', 37, 'rCutSmart', True, False)
BseRI=RestrictionEnzyme('BseRI', 'GAGGAGNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
BseYI=RestrictionEnzyme('BseYI', 'C^CCAG_C', '5′', 37, 'NEB r3.1', False, True)
BsgI=RestrictionEnzyme('BsgI', 'GTGCAGNNNNNNNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
BsiEI=RestrictionEnzyme('BsiEI', 'CG_RY^CG', '3′', 60, 'rCutSmart', True, False)
BsiHKAI=RestrictionEnzyme('BsiHKAI', 'G_WGCW^C', '3′', 65, 'rCutSmart', True, False)
BsiWI=RestrictionEnzyme('BsiWI', 'C^GTAC_G', '5′', 55, 'NEB r3.1', True, True)
BsiWI_HF=RestrictionEnzyme('BsiWI-HF', 'C^GTAC_G', '5′', 37, 'rCutSmart', True, False)
BslI=RestrictionEnzyme('BslI', 'CCNN_NNN^NNGG', '3′', 55, 'rCutSmart', True, False)
BsmAI=RestrictionEnzyme('BsmAI', 'GTCTCN^NNNN_', '5′', 55, 'rCutSmart', True, False)
BsmBI_v2=RestrictionEnzyme('BsmBI-v2', 'CGTCTCN^NNNN_', '5′', 55, 'NEB r3.1', True, True)
BsmFI=RestrictionEnzyme('BsmFI', 'GGGACNNNNNNNNNNN^NNNN_', '5′', 65, 'rCutSmart', False, True)
BsmI=RestrictionEnzyme('BsmI', 'GAATG_CN^', '3′', 65, 'rCutSmart', True, True)
BsoBI=RestrictionEnzyme('BsoBI', 'C^YCGR_G', '5′', 37, 'rCutSmart', True, True)
Bsp1286I=RestrictionEnzyme('Bsp1286I', 'G_DGCH^C', '3′', 37, 'rCutSmart', True, True)
BspCNI=RestrictionEnzyme('BspCNI', 'CTCAGNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
BspDI=RestrictionEnzyme('BspDI', 'AT^CG_AT', '5′', 37, 'rCutSmart', False, True)
BspEI=RestrictionEnzyme('BspEI', 'T^CCGG_A', '5′', 37, 'NEB r3.1', True, True)
BspHI=RestrictionEnzyme('BspHI', 'T^CATG_A', '5′', 37, 'rCutSmart', True, True)
BspMI=RestrictionEnzyme('BspMI', 'ACCTGCNNNN^NNNN_', '5′', 37, 'NEB r3.1', False, True)
BspQI=RestrictionEnzyme('BspQI', 'GCTCTTCN^NNN_', '5′', 50, 'NEB r3.1', True, True)
BsrBI=RestrictionEnzyme('BsrBI', 'CCG_^CTC', 'Blunt', 37, 'rCutSmart', True, True)
BsrDI=RestrictionEnzyme('BsrDI', 'GCAATG_NN^', '3′', 37, 'NEB r2.1', True, True)
BsrFI_v2=RestrictionEnzyme('BsrFI-v2', 'R^CCGG_Y', '5′', 37, 'rCutSmart', True, False)
BsrGI=RestrictionEnzyme('BsrGI', 'T^GTAC_A', '5′', 37, 'NEB r2.1', True, True)
BsrGI_HF=RestrictionEnzyme('BsrGI-HF', 'T^GTAC_A', '5′', 37, 'rCutSmart', True, True)
BsrI=RestrictionEnzyme('BsrI', 'ACTG_GN^', '3′', 65, 'NEB r3.1', True, True)
BssHII=RestrictionEnzyme('BssHII', 'G^CGCG_C', '5′', 50, 'rCutSmart', True, True)
BssSI_v2=RestrictionEnzyme('BssSI-v2', 'C^ACGA_G', '5′', 37, 'rCutSmart', True, False)
BstAPI=RestrictionEnzyme('BstAPI', 'GCAN_NNN^NTGC', '3′', 60, 'rCutSmart', False, True)
BstBI=RestrictionEnzyme('BstBI', 'TT^CG_AA', '5′', 65, 'rCutSmart', True, False)
BstEII=RestrictionEnzyme('BstEII', 'G^GTNAC_C', '5′', 60, 'NEB r3.1', True, False)
BstEII_HF=RestrictionEnzyme('BstEII-HF', 'G^GTNAC_C', '5′', 37, 'rCutSmart', True, False)
BstNI=RestrictionEnzyme('BstNI', 'CC^W_GG', '5′', 60, 'NEB r3.1', True, False)
BstUI=RestrictionEnzyme('BstUI', 'CG_^CG', 'Blunt', 60, 'rCutSmart', True, False)
BstXI=RestrictionEnzyme('BstXI', 'CCAN_NNNN^NTGG', '3′', 37, 'NEB r3.1', True, True)
BstYI=RestrictionEnzyme('BstYI', 'R^GATC_Y', '5′', 60, 'rCutSmart', True, False)
BstZ17I_HF=RestrictionEnzyme('BstZ17I-HF', 'GTA_^TAC', 'Blunt', 37, 'rCutSmart', True, False)
Bsu36I=RestrictionEnzyme('Bsu36I', 'CC^TNA_GG', '5′', 37, 'rCutSmart', True, True)
BtgI=RestrictionEnzyme('BtgI', 'C^CRYG_G', '5′', 37, 'rCutSmart', True, True)
BtgZI=RestrictionEnzyme('BtgZI', 'GCGATGNNNNNNNNNNN^NNNN_', '5′', 60, 'rCutSmart', False, True)
BtsCI=RestrictionEnzyme('BtsCI', 'GGATG_NN^', '3′', 50, 'rCutSmart', True, True)
BtsI_v2=RestrictionEnzyme('BtsI-v2', 'GCAGTG_NN^', '3′', 37, 'rCutSmart', True, False)
BtsIMutI=RestrictionEnzyme('BtsIMutI', 'CAGTG_NN^', '3′', 55, 'rCutSmart', False, True)
Cac8I=RestrictionEnzyme('Cac8I', 'GCN_^NGC', 'Blunt', 37, 'rCutSmart', True, True)
ClaI=RestrictionEnzyme('ClaI', 'AT^CG_AT', '5′', 37, 'rCutSmart', True, True)
CspCI=RestrictionEnzyme('CspCI', '_NN^NNNNNNNNNNNNCAANNNNNGTGGNNNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
CviAII=RestrictionEnzyme('CviAII', 'C^AT_G', '5′', 25, 'rCutSmart', True, True)
CviKI_1=RestrictionEnzyme('CviKI-1', 'RG_^CY', 'Blunt', 37, 'rCutSmart', False, False)
CviQI=RestrictionEnzyme('CviQI', 'G^TA_C', '5′', 25, 'NEB r3.1', True, False)
DdeI=RestrictionEnzyme('DdeI', 'C^TNA_G', '5′', 37, 'rCutSmart', True, True)
DpnI=RestrictionEnzyme('DpnI', 'GA_^TC', 'Blunt', 37, 'rCutSmart', True, True)
DpnII=RestrictionEnzyme('DpnII', '^GATC_', '5′', 37, 'NEB U', True, True)
DraI=RestrictionEnzyme('DraI', 'TTT_^AAA', 'Blunt', 37, 'rCutSmart', True, True)
DraIII_HF=RestrictionEnzyme('DraIII-HF', 'CAC_NNN^GTG', '3′', 37, 'rCutSmart', True, False)
DrdI=RestrictionEnzyme('DrdI', 'GACNN_NN^NNGTC', '3′', 37, 'rCutSmart', True, True)
EaeI=RestrictionEnzyme('EaeI', 'Y^GGCC_R', '5′', 37, 'rCutSmart', False, True)
EagI_HF=RestrictionEnzyme('EagI-HF', 'C^GGCC_G', '5′', 37, 'rCutSmart', True, True)
EarI=RestrictionEnzyme('EarI', 'CTCTTCN^NNN_', '5′', 37, 'rCutSmart', True, True)
EciI=RestrictionEnzyme('EciI', 'GGCGGANNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', False, True)
Eco53kI=RestrictionEnzyme('Eco53kI', 'GAG_^CTC', 'Blunt', 37, 'rCutSmart', True, True)
EcoNI=RestrictionEnzyme('EcoNI', 'CCTNN^N_NNAGG', '5′', 37, 'rCutSmart', True, True)
EcoO109I=RestrictionEnzyme('EcoO109I', 'RG^GNC_CY', '5′', 37, 'rCutSmart', True, True)
EcoRI=RestrictionEnzyme('EcoRI', 'G^AATT_C', '5′', 37, 'NEB U', True, True)
EcoRI_HF=RestrictionEnzyme('EcoRI-HF', 'G^AATT_C', '5′', 37, 'rCutSmart', True, True)
EcoRV=RestrictionEnzyme('EcoRV', 'GAT_^ATC', 'Blunt', 37, 'NEB r3.1', True, True)
EcoRV_HF=RestrictionEnzyme('EcoRV-HF', 'GAT_^ATC', 'Blunt', 37, 'rCutSmart', True, True)
Esp3I=RestrictionEnzyme('Esp3I', 'CGTCTCN^NNNN_', '5′', 37, 'rCutSmart', True, True)
FatI=RestrictionEnzyme('FatI', '^CATG_', '5′', 55, 'NEB r2.1', False, True)
FauI=RestrictionEnzyme('FauI', 'CCCGCNNNN^NN_', '5′', 55, 'rCutSmart', False, True)
Fnu4HI=RestrictionEnzyme('Fnu4HI', 'GC^N_GC', '5′', 37, 'rCutSmart', True, False)
FokI=RestrictionEnzyme('FokI', 'GGATGNNNNNNNNNN^NNNN_', '5′', 37, 'rCutSmart', False, True)
FseI=RestrictionEnzyme('FseI', 'GG_CCGG^CC', '3′', 37, 'rCutSmart', True, True)
FspEI=RestrictionEnzyme('FspEI', 'CCNNNNNNNNNNNNN^NNNN_', '5′', 37, 'rCutSmart', False, True)
FspI=RestrictionEnzyme('FspI', 'TGC_^GCA', 'Blunt', 37, 'rCutSmart', True, False)
HaeII=RestrictionEnzyme('HaeII', 'R_GCGC^Y', '3′', 37, 'rCutSmart', True, True)
HaeIII=RestrictionEnzyme('HaeIII', 'GG_^CC', 'Blunt', 37, 'rCutSmart', True, True)
HgaI=RestrictionEnzyme('HgaI', 'GACGCNNNNNN^NNNNN_', '5′', 37, 'NEB r1.1', False, True)
HhaI=RestrictionEnzyme('HhaI', 'G_CG^C', '3′', 37, 'rCutSmart', True, True)
HinP1I=RestrictionEnzyme('HinP1I', 'G^CG_C', '5′', 37, 'rCutSmart', True, True)
HincII=RestrictionEnzyme('HincII', 'GTY_^RAC', 'Blunt', 37, 'rCutSmart', True, True)
HindIII=RestrictionEnzyme('HindIII', 'A^AGCT_T', '5′', 37, 'NEB r2.1', False, True)
HindIII_HF=RestrictionEnzyme('HindIII-HF', 'A^AGCT_T', '5′', 37, 'rCutSmart', True, True)
HinfI=RestrictionEnzyme('HinfI', 'G^ANT_C', '5′', 37, 'rCutSmart', True, True)
HpaI=RestrictionEnzyme('HpaI', 'GTT_^AAC', 'Blunt', 37, 'rCutSmart', False, False)
HpaII=RestrictionEnzyme('HpaII', 'C^CG_G', '5′', 37, 'rCutSmart', True, True)
HphI=RestrictionEnzyme('HphI', 'GGTGANNNNNNNN_N^', '3′', 37, 'rCutSmart', True, True)
Hpy166II=RestrictionEnzyme('Hpy166II', 'GTN_^NAC', 'Blunt', 37, 'rCutSmart', True, True)
Hpy188I=RestrictionEnzyme('Hpy188I', 'TC_N^GA', '3′', 37, 'rCutSmart', False, True)
Hpy188III=RestrictionEnzyme('Hpy188III', 'TC^NN_GA', '5′', 37, 'rCutSmart', False, True)
Hpy99I=RestrictionEnzyme('Hpy99I', '_CGWCG^', '3′', 37, 'rCutSmart', False, True)
HpyAV=RestrictionEnzyme('HpyAV', 'CCTTCNNNNNN_N^', '3′', 37, 'rCutSmart', True, True)
HpyCH4III=RestrictionEnzyme('HpyCH4III', 'AC_N^GT', '3′', 37, 'rCutSmart', False, True)
HpyCH4IV=RestrictionEnzyme('HpyCH4IV', 'A^CG_T', '5′', 37, 'rCutSmart', True, True)
HpyCH4V=RestrictionEnzyme('HpyCH4V', 'TG_^CA', 'Blunt', 37, 'rCutSmart', True, True)
I_CeuI=RestrictionEnzyme('I-CeuI', 'TAACTATAACGGTC_CTAA^GGTAGCGAA', '3′', 37, 'rCutSmart', False, True)
I_SceI=RestrictionEnzyme('I-SceI', 'TAGGG_ATAA^CAGGGTAAT', '3′', 37, 'rCutSmart', False, True)
KasI=RestrictionEnzyme('KasI', 'G^GCGC_C', '5′', 37, 'rCutSmart', False, True)
KpnI=RestrictionEnzyme('KpnI', 'G_GTAC^C', '3′', 37, 'NEB r1.1', False, False)
KpnI_HF=RestrictionEnzyme('KpnI-HF', 'G_GTAC^C', '3′', 37, 'rCutSmart', True, False)
LpnPI=RestrictionEnzyme('LpnPI', 'CCDGNNNNNNNNNNN^NNNN_', '5′', 37, 'rCutSmart', False, True)
MboI=RestrictionEnzyme('MboI', '^GATC_', '5′', 37, 'rCutSmart', True, True)
MboII=RestrictionEnzyme('MboII', 'GAAGANNNNNNNN_N^', '3′', 37, 'rCutSmart', True, True)
MfeI=RestrictionEnzyme('MfeI', 'C^AATT_G', '5′', 37, 'rCutSmart', False, False)
MfeI_HF=RestrictionEnzyme('MfeI-HF', 'C^AATT_G', '5′', 37, 'rCutSmart', True, False)
MluCI=RestrictionEnzyme('MluCI', '^AATT_', '5′', 37, 'rCutSmart', True, False)
MluI=RestrictionEnzyme('MluI', 'A^CGCG_T', '5′', 37, 'NEB r3.1', True, True)
MluI_HF=RestrictionEnzyme('MluI-HF', 'A^CGCG_T', '5′', 37, 'rCutSmart', True, False)
MlyI=RestrictionEnzyme('MlyI', 'GAGTCNNNNNN_^', 'Blunt', 37, 'rCutSmart', True, True)
MmeI=RestrictionEnzyme('MmeI', 'TCCRACNNNNNNNNNNNNNNNNNNN_NN^', '3′', 37, 'rCutSmart', True, True)
MnlI=RestrictionEnzyme('MnlI', 'CCTCNNNNNNN_N^', '3′', 37, 'rCutSmart', True, True)
MscI=RestrictionEnzyme('MscI', 'TGG_^CCA', 'Blunt', 37, 'rCutSmart', False, True)
MseI=RestrictionEnzyme('MseI', 'T^TA_A', '5′', 37, 'rCutSmart', True, True)
MslI=RestrictionEnzyme('MslI', 'CAYNN_^NNRTG', 'Blunt', 37, 'rCutSmart', True, True)
MspA1I=RestrictionEnzyme('MspA1I', 'CMG_^CKG', 'Blunt', 37, 'rCutSmart', True, True)
MspI=RestrictionEnzyme('MspI', 'C^CG_G', '5′', 37, 'rCutSmart', True, False)
MspJI=RestrictionEnzyme('MspJI', 'CNNRNNNNNNNNNN^NNNN_', '5′', 37, 'rCutSmart', False, True)
MwoI=RestrictionEnzyme('MwoI', 'GCNN_NNN^NNGC', '3′', 60, 'rCutSmart', True, False)
NaeI=RestrictionEnzyme('NaeI', 'GCC_^GGC', 'Blunt', 37, 'rCutSmart', False, False)
NarI=RestrictionEnzyme('NarI', 'GG^CG_CC', '5′', 37, 'rCutSmart', False, True)
NciI=RestrictionEnzyme('NciI', 'CC^S_GG', '5′', 37, 'rCutSmart', True, False)
NcoI=RestrictionEnzyme('NcoI', 'C^CATG_G', '5′', 37, 'NEB r3.1', True, True)
NcoI_HF=RestrictionEnzyme('NcoI-HF', 'C^CATG_G', '5′', 37, 'rCutSmart', True, True)
NdeI=RestrictionEnzyme('NdeI', 'CA^TA_TG', '5′', 37, 'rCutSmart', True, True)
NgoMIV=RestrictionEnzyme('NgoMIV', 'G^CCGG_C', '5′', 37, 'rCutSmart', True, False)
NheI_HF=RestrictionEnzyme('NheI-HF', 'G^CTAG_C', '5′', 37, 'rCutSmart', True, True)
NlaIII=RestrictionEnzyme('NlaIII', '_CATG^', '3′', 37, 'rCutSmart', True, True)
NlaIV=RestrictionEnzyme('NlaIV', 'GGN_^NCC', 'Blunt', 37, 'rCutSmart', False, True)
NmeAIII=RestrictionEnzyme('NmeAIII', 'GCCGAGNNNNNNNNNNNNNNNNNNNN_N^', '3′', 37, 'rCutSmart', False, True)
NotI=RestrictionEnzyme('NotI', 'GC^GGCC_GC', '5′', 37, 'NEB r3.1', True, True)
NotI_HF=RestrictionEnzyme('NotI-HF', 'GC^GGCC_GC', '5′', 37, 'rCutSmart', True, True)
NruI=RestrictionEnzyme('NruI', 'TCG_^CGA', 'Blunt', 37, 'NEB r3.1', True, False)
NruI_HF=RestrictionEnzyme('NruI-HF', 'TCG_^CGA', 'Blunt', 37, 'rCutSmart', True, False)
NsiI=RestrictionEnzyme('NsiI', 'A_TGCA^T', '3′', 37, 'NEB r3.1', True, True)
NsiI_HF=RestrictionEnzyme('NsiI-HF', 'A_TGCA^T', '3′', 37, 'rCutSmart', True, True)
NspI=RestrictionEnzyme('NspI', 'R_CATG^Y', '3′', 37, 'rCutSmart', True, True)
Nt_AlwI=RestrictionEnzyme('Nt.AlwI', 'GGATCNNNN^', '', 37, 'rCutSmart', False, True)
Nt_BbvCI=RestrictionEnzyme('Nt.BbvCI', 'CC^TCAGC', '', 37, 'rCutSmart', False, True)
Nt_BsmAI=RestrictionEnzyme('Nt.BsmAI', 'GTCTCN^', '', 37, 'rCutSmart', False, True)
Nt_BspQI=RestrictionEnzyme('Nt.BspQI', 'GCTCTTCN^', '', 50, 'NEB r3.1', False, True)
Nt_BstNBI=RestrictionEnzyme('Nt.BstNBI', 'GAGTCNNNN^', '', 55, 'NEB r3.1', False, True)
Nt_CviPII=RestrictionEnzyme('Nt.CviPII', '^CCD', '', 37, 'rCutSmart', False, True)
PI_PspI=RestrictionEnzyme('PI-PspI', 'TGGCAAACAGCTA_TTAT^GGGTATTATGGGT', '3′', 65, 'NEB U', False, False)
PI_SceI=RestrictionEnzyme('PI-SceI', 'ATCTATGTCGG_GTGC^GGAGAAAGAGGTAATGAAATGG', '3′', 37, 'NEB U', False, True)
PacI=RestrictionEnzyme('PacI', 'TTA_AT^TAA', '3′', 37, 'rCutSmart', True, True)
PaeR7I=RestrictionEnzyme('PaeR7I', 'C^TCGA_G', '5′', 37, 'rCutSmart', True, False)
PaqCI=RestrictionEnzyme('PaqCI', 'CACCTGCNNNN^NNNN_', '5′', 37, 'rCutSmart', False, True)
PciI=RestrictionEnzyme('PciI', 'A^CATG_T', '5′', 37, 'NEB r3.1', False, True)
PflFI=RestrictionEnzyme('PflFI', 'GACN^N_NGTC', '5′', 37, 'rCutSmart', True, True)
PflMI=RestrictionEnzyme('PflMI', 'CCAN_NNN^NTGG', '3′', 37, 'NEB r3.1', True, True)
PleI=RestrictionEnzyme('PleI', 'GAGTCNNNN^N_', '5′', 37, 'rCutSmart', False, True)
PluTI=RestrictionEnzyme('PluTI', 'G_GCGC^C', '3′', 37, 'rCutSmart', False, True)
PmeI=RestrictionEnzyme('PmeI', 'GTTT_^AAAC', 'Blunt', 37, 'rCutSmart', True, True)
PmlI=RestrictionEnzyme('PmlI', 'CAC_^GTG', 'Blunt', 37, 'rCutSmart', True, True)
PpuMI=RestrictionEnzyme('PpuMI', 'RG^GWC_CY', '5′', 37, 'rCutSmart', True, False)
PshAI=RestrictionEnzyme('PshAI', 'GACNN_^NNGTC', 'Blunt', 37, 'rCutSmart', True, True)
PsiI_v2=RestrictionEnzyme('PsiI-v2', 'TTA_^TAA', 'Blunt', 37, 'rCutSmart', True, True)
PspGI=RestrictionEnzyme('PspGI', '^CCWGG_', '5′', 75, 'rCutSmart', False, False)
PspOMI=RestrictionEnzyme('PspOMI', 'G^GGCC_C', '5′', 37, 'rCutSmart', False, True)
PspXI=RestrictionEnzyme('PspXI', 'VC^TCGA_GB', '5′', 37, 'rCutSmart', False, False)
PstI=RestrictionEnzyme('PstI', 'C_TGCA^G', '3′', 37, 'NEB r3.1', True, True)
PstI_HF=RestrictionEnzyme('PstI-HF', 'C_TGCA^G', '3′', 37, 'rCutSmart', True, False)
PvuI=RestrictionEnzyme('PvuI', 'CG_AT^CG', '3′', 37, 'NEB r3.1', True, False)
PvuI_HF=RestrictionEnzyme('PvuI-HF', 'CG_AT^CG', '3′', 37, 'rCutSmart', True, False)
PvuII=RestrictionEnzyme('PvuII', 'CAG_^CTG', 'Blunt', 37, 'NEB r3.1', True, False)
PvuII_HF=RestrictionEnzyme('PvuII-HF', 'CAG_^CTG', 'Blunt', 37, 'rCutSmart', True, False)
RsaI=RestrictionEnzyme('RsaI', 'GT_^AC', 'Blunt', 37, 'rCutSmart', True, False)
RsrII=RestrictionEnzyme('RsrII', 'CG^GWC_CG', '5′', 37, 'rCutSmart', False, True)
SacI=RestrictionEnzyme('SacI', 'G_AGCT^C', '3′', 37, 'NEB r1.1', True, True)
SacI_HF=RestrictionEnzyme('SacI-HF', 'G_AGCT^C', '3′', 37, 'rCutSmart', True, True)
SacII=RestrictionEnzyme('SacII', 'CC_GC^GG', '3′', 37, 'rCutSmart', True, True)
SalI=RestrictionEnzyme('SalI', 'G^TCGA_C', '5′', 37, 'NEB r3.1', True, True)
SalI_HF=RestrictionEnzyme('SalI-HF', 'G^TCGA_C', '5′', 37, 'rCutSmart', True, True)
SapI=RestrictionEnzyme('SapI', 'GCTCTTCN^NNN_', '5′', 37, 'rCutSmart', True, True)
Sau3AI=RestrictionEnzyme('Sau3AI', '^GATC_', '5′', 37, 'NEB r1.1', False, True)
Sau96I=RestrictionEnzyme('Sau96I', 'G^GNC_C', '5′', 37, 'rCutSmart', False, True)
SbfI=RestrictionEnzyme('SbfI', 'CC_TGCA^GG', '3′', 37, 'rCutSmart', True, True)
SbfI_HF=RestrictionEnzyme('SbfI-HF', 'CC_TGCA^GG', '3′', 37, 'rCutSmart', True, True)
ScaI_HF=RestrictionEnzyme('ScaI-HF', 'AGT_^ACT', 'Blunt', 37, 'rCutSmart', True, True)
ScrFI=RestrictionEnzyme('ScrFI', 'CC^N_GG', '5′', 37, 'rCutSmart', False, True)
SexAI=RestrictionEnzyme('SexAI', 'A^CCWGG_T', '5′', 37, 'rCutSmart', False, True)
SfaNI=RestrictionEnzyme('SfaNI', 'GCATCNNNNNN^NNNN_', '5′', 37, 'NEB r3.1', False, True)
SfcI=RestrictionEnzyme('SfcI', 'C^TRYA_G', '5′', 37, 'rCutSmart', False, True)
SfiI=RestrictionEnzyme('SfiI', 'GGCCN_NNN^NGGCC', '3′', 50, 'rCutSmart', True, False)
SfoI=RestrictionEnzyme('SfoI', 'GGC_^GCC', 'Blunt', 37, 'rCutSmart', True, False)
SgrAI=RestrictionEnzyme('SgrAI', 'CR^CCGG_YG', '5′', 37, 'rCutSmart', False, True)
SmaI=RestrictionEnzyme('SmaI', 'CCC_^GGG', 'Blunt', 37, 'rCutSmart', True, True)
SmlI=RestrictionEnzyme('SmlI', 'C^TYRA_G', '5′', 55, 'rCutSmart', False, False)
SnaBI=RestrictionEnzyme('SnaBI', 'TAC_^GTA', 'Blunt', 37, 'rCutSmart', False, True)
SpeI=RestrictionEnzyme('SpeI', 'A^CTAG_T', '5′', 37, 'rCutSmart', True, True)
SpeI_HF=RestrictionEnzyme('SpeI-HF', 'A^CTAG_T', '5′', 37, 'rCutSmart', True, True)
SphI=RestrictionEnzyme('SphI', 'G_CATG^C', '3′', 37, 'NEB r2.1', False, True)
SphI_HF=RestrictionEnzyme('SphI-HF', 'G_CATG^C', '3′', 37, 'rCutSmart', True, True)
SrfI=RestrictionEnzyme('SrfI', 'GCCC_^GGGC', 'Blunt', 37, 'rCutSmart', True, True)
SspI=RestrictionEnzyme('SspI', 'AAT_^ATT', 'Blunt', 37, 'NEB U', True, True)
SspI_HF=RestrictionEnzyme('SspI-HF', 'AAT_^ATT', 'Blunt', 37, 'rCutSmart', True, True)
StuI=RestrictionEnzyme('StuI', 'AGG_^CCT', 'Blunt', 37, 'rCutSmart', True, False)
StyD4I=RestrictionEnzyme('StyD4I', '^CCNGG_', '5′', 37, 'rCutSmart', True, True)
StyI_HF=RestrictionEnzyme('StyI-HF', 'C^CWWG_G', '5′', 37, 'rCutSmart', True, True)
SwaI=RestrictionEnzyme('SwaI', 'ATTT_^AAAT', 'Blunt', 25, 'NEB r3.1', True, True)
TaqI_v2=RestrictionEnzyme('TaqI-v2', 'T^CG_A', '5′', 65, 'rCutSmart', True, False)
TfiI=RestrictionEnzyme('TfiI', 'G^AWT_C', '5′', 65, 'rCutSmart', True, False)
TseI=RestrictionEnzyme('TseI', 'G^CWG_C', '5′', 65, 'rCutSmart', True, False)
Tsp45I=RestrictionEnzyme('Tsp45I', '^GTSAC_', '5′', 65, 'rCutSmart', False, False)
TspMI=RestrictionEnzyme('TspMI', 'C^CCGG_G', '5′', 75, 'rCutSmart', True, False)
TspRI=RestrictionEnzyme('TspRI', '_NNCASTGNN^', '3′', 65, 'rCutSmart', True, False)
Tth111I=RestrictionEnzyme('Tth111I', 'GACN^N_NGTC', '5′', 65, 'rCutSmart', True, False)
XbaI=RestrictionEnzyme('XbaI', 'T^CTAG_A', '5′', 37, 'rCutSmart', True, True)
XcmI=RestrictionEnzyme('XcmI', 'CCANNNN_N^NNNNTGG', '3′', 37, 'NEB r2.1', False, True)
XhoI=RestrictionEnzyme('XhoI', 'C^TCGA_G', '5′', 37, 'rCutSmart', True, True)
XmaI=RestrictionEnzyme('XmaI', 'C^CCGG_G', '5′', 37, 'rCutSmart', True, True)
XmnI=RestrictionEnzyme('XmnI', 'GAANN_^NNTTC', 'Blunt', 37, 'rCutSmart', True, True)
ZraI=RestrictionEnzyme('ZraI', 'GAC_^GTC', 'Blunt', 37, 'rCutSmart', False, True)
NEB_enzymes_list = [AatII,AbaSI,Acc65I,AccI,AciI,AclI,AcuI,AfeI,AflII,AflIII,AgeI,AgeI_HF,AhdI,AleI_v2,AluI,AlwI,AlwNI,ApaI,ApaLI,ApeKI,ApoI,ApoI_HF,AscI,AseI,AsiSI,AvaI,AvaII,AvrII,BaeGI,BaeI,BamHI,BamHI_HF,BanI,BanII,BbsI,BbsI_HF,BbvCI,BbvI,BccI,BceAI,BcgI,BciVI,BclI,BclI_HF,BcoDI,BfaI,BfuAI,BglI,BglII,BlpI,BmgBI,BmrI,BmtI,BmtI_HF,BpmI,Bpu10I,BpuEI,BsaAI,BsaBI,BsaHI,BsaI_HFv2,BsaJI,BsaWI,BsaXI,BseRI,BseYI,BsgI,BsiEI,BsiHKAI,BsiWI,BsiWI_HF,BslI,BsmAI,BsmBI_v2,BsmFI,BsmI,BsoBI,Bsp1286I,BspCNI,BspDI,BspEI,BspHI,BspMI,BspQI,BsrBI,BsrDI,BsrFI_v2,BsrGI,BsrGI_HF,BsrI,BssHII,BssSI_v2,BstAPI,BstBI,BstEII,BstEII_HF,BstNI,BstUI,BstXI,BstYI,BstZ17I_HF,Bsu36I,BtgI,BtgZI,BtsCI,BtsI_v2,BtsIMutI,Cac8I,ClaI,CspCI,CviAII,CviKI_1,CviQI,DdeI,DpnI,DpnII,DraI,DraIII_HF,DrdI,EaeI,EagI_HF,EarI,EciI,Eco53kI,EcoNI,EcoO109I,EcoRI,EcoRI_HF,EcoRV,EcoRV_HF,Esp3I,FatI,FauI,Fnu4HI,FokI,FseI,FspEI,FspI,HaeII,HaeIII,HgaI,HhaI,HinP1I,HincII,HindIII,HindIII_HF,HinfI,HpaI,HpaII,HphI,Hpy166II,Hpy188I,Hpy188III,Hpy99I,HpyAV,HpyCH4III,HpyCH4IV,HpyCH4V,I_CeuI,I_SceI,KasI,KpnI,KpnI_HF,LpnPI,MboI,MboII,MfeI,MfeI_HF,MluCI,MluI,MluI_HF,MlyI,MmeI,MnlI,MscI,MseI,MslI,MspA1I,MspI,MspJI,MwoI,NaeI,NarI,NciI,NcoI,NcoI_HF,NdeI,NgoMIV,NheI_HF,NlaIII,NlaIV,NmeAIII,NotI,NotI_HF,NruI,NruI_HF,NsiI,NsiI_HF,NspI,Nt_AlwI,Nt_BbvCI,Nt_BsmAI,Nt_BspQI,Nt_BstNBI,Nt_CviPII,PI_PspI,PI_SceI,PacI,PaeR7I,PaqCI,PciI,PflFI,PflMI,PleI,PluTI,PmeI,PmlI,PpuMI,PshAI,PsiI_v2,PspGI,PspOMI,PspXI,PstI,PstI_HF,PvuI,PvuI_HF,PvuII,PvuII_HF,RsaI,RsrII,SacI,SacI_HF,SacII,SalI,SalI_HF,SapI,Sau3AI,Sau96I,SbfI,SbfI_HF,ScaI_HF,ScrFI,SexAI,SfaNI,SfcI,SfiI,SfoI,SgrAI,SmaI,SmlI,SnaBI,SpeI,SpeI_HF,SphI,SphI_HF,SrfI,SspI,SspI_HF,StuI,StyD4I,StyI_HF,SwaI,TaqI_v2,TfiI,TseI,Tsp45I,TspMI,TspRI,Tth111I,XbaI,XcmI,XhoI,XmaI,XmnI,ZraI]
_NEB_enzymes = {enzyme.name: enzyme for enzyme in NEB_enzymes_list}